[package]
name = "rust_notebook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"
rocket_codegen = "0.5.0"
tokio = { version = "1", features = ["full"] }